### PR TITLE
updated gnutls remote and include libifaddrs on Android

### PR DESCRIPTION
**Pull request by Rugvip**

### CODE REVIEW

**Comment by Rugvip** [comment]
Some updates until we get the cerbero build working.
I'm not sure about the libifaddrs change, I've been using it to build for Android, but the library needs to the openwebrtc build as well. How is that problem handled in cerbero?

**Comment by Rugvip** [comment]
Should fix EricssonResearch/openwebrtc#233

**Comment by superdump** [comment]
You can land the gnutls change at least.

**Comment by superdump** [comment]
It seems there is a local ifaddrs implementation in cerbero: https://github.com/nirbheek/cerbero/tree/openwebrtc/recipes/libusrsctp

**Comment by Rugvip** [comment]
Right, and it's just copied into the rest of the lib. I'll update this PR with a similar solution

**Comment by Rugvip** [comment]
Updated with new lib-free solution!

**Comment by superdump** [comment]
Merged.

**Pull request closed without merging**
