### PR TITLE
Part of fixing interop with newest Firefox (crypto related).

### PR DESCRIPTION
**Pull request by stefhak**
I've not tested anything more than FF - OWR interop on OSX. More tests should be done on more platforms before landing.
https://github.com/EricssonResearch/openwebrtc-gst-plugins/pull/22/files must also be merged for things to work.

### CODE REVIEW

**Comment by sdroege** [comment]
I was using 1.0.2 before with Owr and had no problem. Makes sense to update it

@nirbheek please also update it in cerbero

**Comment by stefhak** [comment]
Honestly, I think we should land this one. Sooner or later the old version will give us issues. And the testing I've done has not indicated that this would result in any issues.

**Comment by sdroege** [comment]
I agree. @nirbheek , what's the status with 1.0.2 in cerbero?

**Comment by superdump** [comment]
:+1: Though the commit message should be something like:
```
dependencies: Update OpenSSL to 1.0.2

This is required to fix interoperability with Firefox Nightlies (at the time of writing.)
```

Perhaps even some comment in the commit message about what exactly OpenSSL 1.0.2 is needed for. The contents of the commit itself is completely approved. :smile:

**Comment by stefhak** [comment]
@superdump: are you proposing I update the PR (to get a reasonable commit message)? I can do that.

**Comment by superdump** [comment]
@stefhak Yes please. And when you've done that, I'll land it.

**Comment by stefhak** [comment]
Great! It will take me a while (I'm still learning git), but I'll do it. I don't think it is urgent.

**Comment by stefhak** [comment]
So, I did some git things. I don't know if I got it right, but hope so.

**Comment by sdroege** [comment]
Thanks, merged :)

**Pull request closed without merging**
